name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - run: make cover
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml

      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
